name: Build openDAQ packages


on:
  push:
    branches: [release/**]

  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

  workflow_call:
    inputs:
      cmake_preset:
        required: false
        type: string
      ctest_preset:
        required: false
        type: string

env:
  cmake_preset: package
  python_versions: 3.8 3.14
  windows_x64_artifact: SdkWindows64
  vm_name: device_simulator
  simulator_app_artifact: SimulatorApp

jobs:
  package_windows:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}
      cancel-in-progress: true
    timeout-minutes: 240
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        include:
          - name: Windows VS 2022 x64 Release
            runner: windows-latest
            cmake-generator: "Visual Studio 17 2022"
            cmake-build-type: Release
            cmake-defines: >-
              -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF
              -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF
              -DOPENDAQ_ENABLE_TESTS=OFF
              -DOPENDAQ_ENABLE_TEST_UTILS=OFF
              -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              -DOPENDAQ_ENABLE_OPCUA=OFF
              -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
              -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              -DDAQMODULES_REF_FB_MODULE=OFF
              -DDAQMODULES_REF_DEVICE_MODULE=OFF
              -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
            cpack-generator: NSIS
            disable-ccache: true
            enable-32bit: false
            generate-python-bindings: true
            generate-csharp-bindings: true

          - name: Windows VS 2022 Win32 Release
            runner: windows-latest
            cmake-generator: "Visual Studio 17 2022"
            cmake-build-type: Release
            cmake-defines: >-
              -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF
              -DOPENDAQ_GENERATE_CSHARP_BINDINGS=OFF
              -DOPENDAQ_ENABLE_TESTS=OFF
              -DOPENDAQ_ENABLE_TEST_UTILS=OFF
              -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              -DOPENDAQ_ENABLE_OPCUA=OFF
              -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
              -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              -DDAQMODULES_REF_FB_MODULE=OFF
              -DDAQMODULES_REF_DEVICE_MODULE=OFF
              -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
            cpack-generator: NSIS
            disable-ccache: true
            enable-32bit: true
            generate-python-bindings: false
            generate-csharp-bindings: false

    outputs:
      # trick for reusable workflow in dotnet_bindings because cannot use env context in "with:"
      # test_path: ''
      windows_x64_artifact_name: ${{ env.windows_x64_artifact }}
      # short_sha: ${{ env.short_sha }}
      short_sha_dotnet: ${{ steps.package-csharp-bindings.outputs.short-sha-dotnet }}

    env:
      short_sha: 'package'  # for .NET Bindings build

    steps:
      # TODO: Remove these 3 steps before merging to openDAQ/openDAQ
      - name: Checkout openDAQ
        if: github.repository != 'openDAQ/openDAQ'
        uses: actions/checkout@v4
        with:
          repository: openDAQ/openDAQ

      - name: Checkout CI actions
        if: github.repository != 'openDAQ/openDAQ'
        uses: actions/checkout@v4
        with:
          path: _ci-sandbox

      - name: Copy CI actions
        if: github.repository != 'openDAQ/openDAQ'
        shell: bash
        run: cp -r _ci-sandbox/.github/actions .github/

      - name: Apply patches
        if: github.repository != 'openDAQ/openDAQ'
        shell: bash
        run: |
          if [ ! -d "_ci-sandbox/.github/patches" ]; then
            echo "No patches directory, nothing to apply"
            exit 0
          fi
          for patch in _ci-sandbox/.github/patches/*.patch; do
            [ -f "$patch" ] && git apply "$patch" && echo "Applied: $patch" || true
          done

      - name: Setup ccache
        if: ${{ matrix.disable-ccache != true }}
        uses: openDAQ/openDAQ-CI-sandbox/.github/actions/ccache-setup@actions/ccache-setup
        with:
          cmake-config-args: ${{ matrix.cmake-defines }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          target-arch: ${{ matrix.enable-32bit == true && 'x86-32' || '' }}

      # TODO: End of sandbox-only steps

      - name: Build SDK
        id: build-sdk
        uses: ./.github/actions/build-sdk
        with:
          additional-dependencies: nsis
          cmake-generator: ${{ matrix.cmake-generator }}
          cmake-config-preset: ${{ env.cmake_preset }}
          cmake-config-args: ${{ matrix.cmake-defines }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          enable-32bit: ${{ matrix.enable-32bit == true }}
          cpack-generator: ${{ matrix.cpack-generator }}
          generate-csharp-bindings: false
          generate-python-bindings: false

      - name: Upload SDK Installer
        uses: actions/upload-artifact@v4
        with:
          name: Package (${{ matrix.name }})
          path: ${{ steps.build-sdk.outputs.package-path }}
          retention-days: 7

      - name: Package Python Bindings
        if: matrix.generate-python-bindings == true
        uses: ./.github/actions/package-bindings-python
        with:
          python-versions: ${{ env.python_versions }}
          build-path: ${{ steps.build-sdk.outputs.build-path }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          package-artifact-name: Wheels (${{ matrix.name }})
          package-artifact-retention-days: 7

      - name: Package C# Bindings
        id: package-csharp-bindings
        if: matrix.generate-csharp-bindings == true
        uses: ./.github/actions/package-bindings-csharp
        with:
          build-path: ${{ steps.build-sdk.outputs.build-path }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          package-artifact-name: ${{ env.windows_x64_artifact }}
          package-artifact-retention-days: 7

  package_linux:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}
      cancel-in-progress: true
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x86_64 GCC Release
            runner: ubuntu-22.04
            additional-dependencies: doxygen graphviz wget zip
            cmake-generator: Ninja
            cmake-build-type: Release
            cmake-defines: >-
              -DOPENDAQ_ENABLE_TESTS=OFF
              -DOPENDAQ_ENABLE_TEST_UTILS=OFF
              -DOPENDAQ_ENABLE_OPCUA=OFF
              -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
              -DDAQMODULES_REF_FB_MODULE=OFF
              -DDAQMODULES_REF_DEVICE_MODULE=OFF
              -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              -DCMAKE_C_COMPILER_LAUNCHER=ccache
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
            disable-ccache: false
            generate-simulator-app: true
            generate-doxygen-doc: true
            generate-csharp-bindings: true

          - name: Linux ARM64 GCC Release
            runner: ubuntu-22.04-arm
            cmake-generator: Ninja
            cmake-build-type: Release
            cmake-defines: >-
              -DOPENDAQ_ENABLE_TESTS=OFF
              -DOPENDAQ_ENABLE_TEST_UTILS=OFF
              -DOPENDAQ_ENABLE_OPCUA=OFF
              -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
              -DDAQMODULES_REF_FB_MODULE=OFF
              -DDAQMODULES_REF_DEVICE_MODULE=OFF
              -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              -DCMAKE_C_COMPILER_LAUNCHER=ccache
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
            disable-ccache: false
            generate-simulator-app: false
            generate-doxygen-doc: false
            generate-csharp-bindings: false
    env:
      CC: gcc
      CXX: g++

    steps:
      # TODO: Remove these 3 steps before merging to openDAQ/openDAQ
      - name: Checkout openDAQ
        if: github.repository != 'openDAQ/openDAQ'
        uses: actions/checkout@v4
        with:
          repository: openDAQ/openDAQ

      - name: Checkout CI actions
        if: github.repository != 'openDAQ/openDAQ'
        uses: actions/checkout@v4
        with:
          path: _ci-sandbox

      - name: Copy CI actions
        if: github.repository != 'openDAQ/openDAQ'
        shell: bash
        run: cp -r _ci-sandbox/.github/actions .github/

      - name: Apply patches
        if: github.repository != 'openDAQ/openDAQ'
        shell: bash
        run: |
          if [ ! -d "_ci-sandbox/.github/patches" ]; then
            echo "No patches directory, nothing to apply"
            exit 0
          fi
          for patch in _ci-sandbox/.github/patches/*.patch; do
            [ -f "$patch" ] && git apply "$patch" && echo "Applied: $patch" || true
          done

      - name: Setup ccache
        if: ${{ matrix.disable-ccache != true }}
        uses: openDAQ/openDAQ-CI-sandbox/.github/actions/ccache-setup@actions/ccache-setup
        with:
          cmake-config-args: ${{ matrix.cmake-defines }}
          cmake-build-type: ${{ matrix.cmake-build-type }}

      # TODO: End of sandbox-only steps

      - name: Build SDK
        id: build-sdk
        uses: ./.github/actions/build-sdk
        with:
          additional-dependencies: ${{ matrix.additional-dependencies }}
          cmake-generator: ${{ matrix.cmake-generator }}
          cmake-config-preset: ${{ env.cmake_preset }}
          cmake-config-args: ${{ matrix.cmake-defines }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          cpack-generator: DEB
          generate-csharp-bindings: false
          generate-python-bindings: false
          generate-simulator-app: false
          generate-doxygen-doc: false

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: Package (${{ matrix.name }})
          path: ${{ steps.build-sdk.outputs.package-path }}
          retention-days: 7

      - name: Build Documentation
        if: matrix.generate-doxygen-doc == true
        shell: bash
        run: |
          cmake -B ${{ steps.build-sdk.outputs.build-path }} -G "${{ matrix.cmake-generator }}" -DOPENDAQ_BUILD_DOCUMENTATION=ON
          cmake --build ${{ steps.build-sdk.outputs.build-path }} --target doc_doxygen
          cd ${{ steps.build-sdk.outputs.build-path }}/doc_doxygen/html
          zip -r ../opendaq_cpp_api_reference.zip .

      - name: Upload API Reference
        if: matrix.generate-doxygen-doc == true
        uses: actions/upload-artifact@v4
        with:
          name: API Reference
          path: ${{ steps.build-sdk.outputs.build-path }}/doc_doxygen/opendaq_cpp_api_reference.zip
          retention-days: 7

      - name: Build Simulator App
        if: matrix.generate-simulator-app == true
        shell: bash
        run: |
          cmake -B ${{ steps.build-sdk.outputs.build-path }} -G "${{ matrix.cmake-generator }}" \
            -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=ON \
            -DDAQMODULES_REF_DEVICE_MODULE=ON \
            -DDAQMODULES_REF_FB_MODULE=ON \
            -DDAQMODULES_OPENDAQ_SERVER_MODULE=ON \
            -DOPENDAQ_ENABLE_NATIVE_STREAMING=ON \
            -DOPENDAQ_ENABLE_OPCUA=ON
          cmake --build ${{ steps.build-sdk.outputs.build-path }} --target application_simulator

      - name: Upload Simulator App
        if: matrix.generate-simulator-app == true
        uses: actions/upload-artifact@v4
        with:
          name: SimulatorApp
          path: ${{ steps.build-sdk.outputs.build-path }}/bin/application_simulator
          retention-days: 7

      - name: Upload binaries for .NET NuGet
        if: matrix.generate-csharp-bindings == true
        uses: actions/upload-artifact@v4
        with:
          name: SdkLinux64
          path: |
            ${{ steps.build-sdk.outputs.build-path }}/bin/*.so
            !${{ steps.build-sdk.outputs.build-path }}/**/opendaq.cpython*
            !${{ steps.build-sdk.outputs.build-path }}/**/*_test_dll.so
          retention-days: 1

  build_macos:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}
      cancel-in-progress: true
    timeout-minutes: 400
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS x86_64 Clang Release
            runner: macos-15-intel
            cmake-generator: Ninja
            cmake-build-type: Release
            cmake-defines: >-
              -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15
              -DOPENDAQ_ENABLE_TESTS=OFF
              -DOPENDAQ_ENABLE_TEST_UTILS=OFF
              -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              -DOPENDAQ_ENABLE_OPCUA=OFF
              -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
              -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              -DDAQMODULES_REF_FB_MODULE=OFF
              -DDAQMODULES_REF_DEVICE_MODULE=OFF
              -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              -DCMAKE_C_COMPILER_LAUNCHER=ccache                                                                                                                                                                    
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache   
            disable-ccache: false

          - name: macOS ARM64 Clang Release
            runner: macos-latest
            cmake-generator: Ninja
            cmake-build-type: Release
            cmake-defines: >-
              -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15
              -DOPENDAQ_ENABLE_TESTS=OFF
              -DOPENDAQ_ENABLE_TEST_UTILS=OFF
              -DOPENDAQ_BUILD_DOCUMENTATION=OFF
              -DOPENDAQ_ENABLE_OPCUA=OFF
              -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF
              -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF
              -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF
              -DDAQMODULES_REF_FB_MODULE=OFF
              -DDAQMODULES_REF_DEVICE_MODULE=OFF
              -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF
              -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF
              -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF
              -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF
              -DCMAKE_C_COMPILER_LAUNCHER=ccache                                                                                                                                                                    
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache   
            disable-ccache: false
    env:
      CC: clang
      CXX: clang++

    steps:
      # TODO: Remove these 3 steps before merging to openDAQ/openDAQ
      - name: Checkout openDAQ
        if: github.repository != 'openDAQ/openDAQ'
        uses: actions/checkout@v4
        with:
          repository: openDAQ/openDAQ

      - name: Checkout CI actions
        if: github.repository != 'openDAQ/openDAQ'
        uses: actions/checkout@v4
        with:
          path: _ci-sandbox

      - name: Copy CI actions
        if: github.repository != 'openDAQ/openDAQ'
        shell: bash
        run: cp -r _ci-sandbox/.github/actions .github/

      - name: Apply patches
        if: github.repository != 'openDAQ/openDAQ'
        shell: bash
        run: |
          if [ ! -d "_ci-sandbox/.github/patches" ]; then
            echo "No patches directory, nothing to apply"
            exit 0
          fi
          for patch in _ci-sandbox/.github/patches/*.patch; do
            [ -f "$patch" ] && git apply "$patch" && echo "Applied: $patch" || true
          done

      - name: Setup ccache
        if: ${{ matrix.disable-ccache != true }}
        uses: openDAQ/openDAQ-CI-sandbox/.github/actions/ccache-setup@actions/ccache-setup
        with:
          cmake-config-args: ${{ matrix.cmake-defines }}
          cmake-build-type: ${{ matrix.cmake-build-type }}

      # TODO: End of sandbox-only steps

      - name: Build SDK
        id: build-sdk
        uses: ./.github/actions/build-sdk
        with:
          additional-dependencies: nsis
          cmake-generator: ${{ matrix.cmake-generator }}
          cmake-config-preset: ${{ env.cmake_preset }}
          cmake-config-args: ${{ matrix.cmake-defines }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          generate-csharp-bindings: false
          generate-python-bindings: false

      - name: Package Python Bindings
        uses: ./.github/actions/package-bindings-python
        with:
          python-versions: ${{ env.python_versions }}
          build-path: ${{ steps.build-sdk.outputs.build-path }}
          cmake-build-type: ${{ matrix.cmake-build-type }}
          package-artifact-name: Wheels (${{ matrix.name }})
          package-artifact-retention-days: 7

  simulator-build:
    runs-on: ubuntu-latest
    name: Simulator build
    needs: [package_linux]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-simulator
      cancel-in-progress: true
    timeout-minutes: 120
    env:
      simulator_directory: simulator

    defaults:
      run:
        working-directory: ${{ env.simulator_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: openDAQ/openDAQ

      - name: Install tools
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install -y virtualbox vagrant

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: Package (Linux x86_64 GCC Release)
          path: ${{ env.simulator_directory }}

      - name: Download simulator app
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.simulator_app_artifact }}
          path: ${{ env.simulator_directory }}

      - name: Display files in working directory
        run: ls -Rhl

      - name: Read openDAQ version
        id: daq_version
        working-directory: .
        run: |
          DAQ_VER=$(cat opendaq_version)
          echo Head openDAQ version: $DAQ_VER
          echo "DAQ_VERSION=$DAQ_VER" >> "$GITHUB_OUTPUT"

      - name: Define simulator name
        id: simulator_name
        run: echo "SIMULATOR_NAME=opendaq-${{ steps.daq_version.outputs.DAQ_VERSION }}_${{ env.vm_name }}" >> "$GITHUB_OUTPUT"

      - name: Find binaries and run vagrant
        run: |
          debfiles=( *.deb )
          vagrant --version
          VM_NAME=${{ steps.simulator_name.outputs.SIMULATOR_NAME }} HOME_PATH=$HOME PACKAGE_NAME=${debfiles[0]} vagrant up
          VM_NAME=${{ steps.simulator_name.outputs.SIMULATOR_NAME }} HOME_PATH=$HOME PACKAGE_NAME=${debfiles[0]} vagrant halt

      - name: vboxmanage modify and compact
        run: |
          vboxmanage modifyvm ${{ steps.simulator_name.outputs.SIMULATOR_NAME }} --audio none --uart1 off --nic1 hostonly --hostonlyadapter1 "VirtualBox Host-Only Ethernet Adapter"
          vboxmanage modifymedium disk "${{ steps.simulator_name.outputs.SIMULATOR_NAME }}.vdi" --compact

      - name: vboxmanage check
        run: |
          vboxmanage list vms
          vboxmanage list hostonlyifs
          vboxmanage list hdds

      - name: export VM to .ova appliance
        run: |
          vboxmanage export ${{ steps.simulator_name.outputs.SIMULATOR_NAME }} -o ${{ steps.simulator_name.outputs.SIMULATOR_NAME }}.ova --options manifest,nomacs
          ls -hl ${{ steps.simulator_name.outputs.SIMULATOR_NAME }}.ova

      - name: Upload OVA image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.simulator_name.outputs.SIMULATOR_NAME }}-ova-image
          path: simulator/${{ steps.simulator_name.outputs.SIMULATOR_NAME }}.ova
          retention-days: 7

      - name: Delete unused artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: ${{ env.simulator_app_artifact }}
