name: Test Reusable Build SDK

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    strategy:
      matrix:
        include:
          - runner: windows-latest
            cmake-generator-name: Visual Studio 17 2022
            cpack-generator-name: NSIS

    uses: ./.github/workflows/reusable-build-sdk.yml
    with:
      runner: ${{ matrix.runner }}
      path: openDAQ
      cmake-generator-name: ${{ matrix.cmake-generator-name }}
      cmake-config-args: -DOPENDAQ_ENABLE_TESTS=ON -DOPENDAQ_BUILD_DOCUMENTATION=OFF -DDAQSIMULATOR_ENABLE_SIMULATOR_APP=OFF -DDAQMODULES_REF_FB_MODULE=OFF -DOPENDAQ_GENERATE_PYTHON_BINDINGS=OFF -DDAQMODULES_REF_DEVICE_MODULE=OFF -DDAQMODULES_AUDIO_DEVICE_MODULE=OFF -DDAQMODULES_OPENDAQ_CLIENT_MODULE=OFF -DDAQMODULES_OPENDAQ_SERVER_MODULE=OFF -DDAQMODULES_BASIC_CSV_RECORDER_MODULE=OFF -DOPENDAQ_ENABLE_OPCUA=OFF -DOPENDAQ_ENABLE_WEBSOCKET_STREAMING=OFF -DOPENDAQ_ENABLE_NATIVE_STREAMING=OFF -DOPENDAQ_MSVC_SINGLE_PROCESS_BUILD=ON
      ctest-enable: true
      ctest-preset: run_tests
      ctest-output-on-failure: true
      cpack-generator-name: ${{ matrix.cpack-generator-name }}
