name: Test Reusable Build SDK

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    strategy:
      matrix:
        include:
          - runner: windows-latest
            cmake-generator-name: Visual Studio 17 2022
            cpack-generator-name: NSIS

    uses: ./.github/workflows/reusable-build-sdk.yml
    with:
      runner: ${{ matrix.runner }}
      path: openDAQ
      cmake-generator-name: ${{ matrix.cmake-generator-name }}
      cmake-preset-name: ci
      cmake-config-args: -DOPENDAQ_MSVC_SINGLE_PROCESS_BUILD=ON -DDAQMODULES_PARQUET_RECORDER_MODULE=ON -DCMAKE_BUILD_TYPE=Release
      ctest-enable: true
      ctest-preset: run_tests
      ctest-output-on-failure: true
      cpack-generator-name: ${{ matrix.cpack-generator-name }}
